{block name="customer_manage_tab_content"}
    <div style="display: none;" class="scroller scroller-left"><span class="icon-chevron-left"></span></div>
    <div style="display: block;" class="scroller scroller-right"><span class="icon-chevron-right"></span></div>
    <div class="wrapper no-margin">
        <ul class="nav nav-tabs list" role="tablist" id="myTab" style="left: 0px;">
            {if $privilege_general.edit_customer eq 1}<li role="presentation" {if $menu.tabmenu == 'REGISTER'}class="active"{/if}><a href="javascript:void(0)" onclick="redirectConfirm('{$url_path}customer/add/%%C-UNAME%%/')" aria-controls="1" role="tab" data-toggle="tab">{$translate.register}</a></li>{/if}
            {*if $user_role eq 1*}
            {if $privilege_general.customer_settings_insurance_fk eq 1}<li {if $menu.tabmenu == 'INSURANCE-FK'}class="active"{/if} role="presentation"><a aria-controls="2" role="tab" data-toggle="tab" href="javascript:void(0)" onclick="redirectConfirm('{$url_path}customer/insurance/fk/%%C-UNAME%%/')">{$translate.insurance}</a></li>{/if}
            {if $privilege_general.customer_settings_insurance_kn eq 1}<li {if $menu.tabmenu == 'INSURANCE-KN'}class="active"{/if} role="presentation"><a aria-controls="3e" role="tab" data-toggle="tab" href="javascript:void(0)" onclick="redirectConfirm('{$url_path}customer/insurance/kn/%%C-UNAME%%/')">{$translate.municipality}</a></li>{/if}
            {if $privilege_general.customer_settings_insurance_tu eq 1}<li {if $menu.tabmenu == 'INSURANCE-TE'}class="active"{/if} role="presentation"><a aria-controls="4" role="tab" data-toggle="tab" href="javascript:void(0)" onclick="redirectConfirm('{$url_path}customer/insurance/te/%%C-UNAME%%/')">{$translate.insurance_te}</a></li>{/if}
            {if $privilege_general.customer_settings_implan eq 1}<li {if $menu.tabmenu == 'IMPLAN'}class="active"{/if} role="presentation"><a aria-controls="5" role="tab" data-toggle="tab" href="javascript:void(0)" onclick="redirectConfirm('{$url_path}customer/implan/%%C-UNAME%%/')">{$translate.implementation_plan}</a></li>{/if}
            {if $privilege_general.customer_settings_deswork eq 1}<li {if $menu.tabmenu == 'DESWORK'}class="active"{/if} role="presentation"><a aria-controls="6" role="tab" data-toggle="tab" href="javascript:void(0)" onclick="redirectConfirm('{$url_path}customer/deswork/%%C-UNAME%%/')">{$translate.description_of_work}</a></li>{/if}
            {if $privilege_general.customer_settings_documentation eq 1}<li {if $menu.tabmenu == 'DOCUMENT'}class="active"{/if} role="presentation"><a aria-controls="7" role="tab" data-toggle="tab" href="javascript:void(0)" onclick="redirectConfirm('{$url_path}customer/documentation/%%C-UNAME%%/')">{$translate.documentation}</a></li>{/if}
            {if $privilege_general.customer_settings_equipment eq 1}<li {if $menu.tabmenu == 'EQUIPMENT'}class="active"{/if} role="presentation"><a aria-controls="8" role="tab" data-toggle="tab" href="javascript:void(0)" onclick="redirectConfirm('{$url_path}customer/equipment/%%C-UNAME%%/')">{$translate.equipment}</a></li>{/if}
            {if $privilege_general.customer_settings_privileges eq 1}<li {if $menu.tabmenu == 'PRIVILEGE'}class="active"{/if} role="presentation"><a aria-controls="9" role="tab" data-toggle="tab" href="javascript:void(0)" onclick="redirectConfirm('{$url_path}customer/privilege/%%C-UNAME%%/')">{$translate.privilege}</a></li>{/if}
            {if $privilege_general.customer_settings_appointment eq 1}<li {if $menu.tabmenu == 'APPOINMENT'}class="active"{/if} role="presentation"><a aria-controls="10" role="tab" data-toggle="tab" href="javascript:void(0)" onclick="redirectConfirm('{$url_path}customer/appoiments/%%C-UNAME%%/')">{$translate.appoiments}</a></li>{/if}
            {if $privilege_general.customer_settings_oncall eq 1}<li {if $menu.tabmenu == 'INCONVINIENCE'}class="active"{/if} role="presentation"><a aria-controls="11" role="tab" data-toggle="tab" href="javascript:void(0)" onclick="redirectConfirm('{$url_path}customer/inconvenient/timings/list/%%C-UNAME%%/')">{$translate.customer_oncall_settings}</a></li>{/if}
            {if $privilege_general.customer_settings_3066 eq 1}{*if $user_role eq 1 or $emp_role_in_customer eq 7*}<li {if $menu.tabmenu == 'F-3066'}class="active"{/if} role="presentation"><a aria-controls="12" role="tab" data-toggle="tab" href="javascript:void(0)" onclick="redirectConfirm('{$url_path}customer/to/employee/3066/%%C-UNAME%%/')">3066</a></li>{/if}
            {if $privilege_general.customer_settings_sick_form_defaults eq 1}{*if $user_role eq 1 or $emp_role_in_customer eq 7*}<li {if $menu.tabmenu == 'SICK-DEFAULT'}class="active"{/if} role="presentation"><a aria-controls="13" role="tab" data-toggle="tab" href="javascript:void(0)" onclick="redirectConfirm('{$url_path}customer/defaults/sick/%%C-UNAME%%/')">{$translate.sick_form_defaults}</a></li>{/if}
            {if $privilege_general.customer_settings_location eq 1}<li {if $menu.tabmenu == 'LOCATION'}class="active"{/if} role="presentation"><a aria-controls="14" role="tab" data-toggle="tab" href="javascript:void(0)" onclick="redirectConfirm('{$url_path}customer/locations/%%C-UNAME%%/')">{$translate.map_location}</a></li>{/if}
            {*/if*}
        </ul>
    </div>
{/block}